#  Bitbucket Pipeline for template engine
image: node:10.15.3
pipelines:
  branches:
    task-*:
      - step:
          name: 1. Scanning Git Secrets 
          script:
            - echo "Installing Git Secrets"
            - cd ${BITBUCKET_CLONE_DIR}/ops
            - source ${BITBUCKET_CLONE_DIR}/ops/ci/clone-git-secrets.sh
            - echo "Scan Git Secrets"
            - cd ${BITBUCKET_CLONE_DIR}
            - source ${BITBUCKET_CLONE_DIR}/ops/ci/git-secrets.sh

    feature-*:
      - step:
          name: 1.Running Initial Tests
          script:
            - echo "Installing Git Secrets"
            - cd ${BITBUCKET_CLONE_DIR}/ops
            - source ${BITBUCKET_CLONE_DIR}/ops/ci/clone-git-secrets.sh
            - cd ${BITBUCKET_CLONE_DIR}/server
            - echo "NPM Installing Packages"
            - npm ci
            - echo "Scan Git Secrets"
            - cd ${BITBUCKET_CLONE_DIR}
            - source ${BITBUCKET_CLONE_DIR}/ops/ci/git-secrets.sh
            - cd ${BITBUCKET_CLONE_DIR}/server
            - echo "Running Test Cases"
            - npm run test

    master:
      - step:
          name: 1.Running Initial Tests
          script:
            - echo "Installing Git Secrets"
            - cd ${BITBUCKET_CLONE_DIR}/ops
            - source ${BITBUCKET_CLONE_DIR}/ops/ci/clone-git-secrets.sh
            - cd ${BITBUCKET_CLONE_DIR}/server
            - echo "NPM Installing Packages"
            - npm ci
            - echo "Building the solution"
            - npm run build
            - echo "Scan Git Secrets"
            - cd ${BITBUCKET_CLONE_DIR}
            - source ${BITBUCKET_CLONE_DIR}/ops/ci/git-secrets.sh
            - cd ${BITBUCKET_CLONE_DIR}/server
            - echo "Running Test Cases"
            - npm run test
            - cp ${BITBUCKET_CLONE_DIR}/Dockerfile ${BITBUCKET_CLONE_DIR}/server
            - cp ${BITBUCKET_CLONE_DIR}/.dockerignore ${BITBUCKET_CLONE_DIR}/server
          artifacts:
            - server/**
      - step:
          name: 2. Create AWS ECR Registry and Push Artifacts
          image: python:latest
          services:
            - docker
          script:
            - source ${BITBUCKET_CLONE_DIR}/ops/ci/push-docker-image-ecr.sh ${BITBUCKET_CLONE_DIR}/server
      - step:
          name: 3. Creating tag to commit
          script:
            - bash ${BITBUCKET_CLONE_DIR}/ops/ci/create-tag.sh
    